### ISSUE TITLE
Use Result with all query API

### ISSUE THREAD

**Issue by mc1098** [mc1098/sap#4]
`by_label_text` query has a decent error type returned within a Result that makes it a more pleasant experience when a test fails unexpectedly. 
`by_aria` is the recommended query, as it helps promote accessible design, but it is the hardest to diagnose why a test may have failed unexpectedly. This could be due to a misunderstanding of accessible name or due to a small typo in the test, or even where sap differs from a particular standard or implementation when calculating the accessible name. 
It is probably useful to display the DOM in a formatted way so that when a test fails the user is able to review the state of the DOM when the failure occurred (this will likely be a separate issue/PR added to all queries). 

- [x] by_aria (PR #15)
- [x] by_display_value (PR #13)
- [x] by_placeholder_text (PR #11)
- [x] by_text (PR #8)
